# .swiftlint.yml
included:
  - Shared

excluded:
  - Config/Secrets
  - DerivedData
  - Carthage
  - Pods
  - .build
  - Packages

# Keep CI signal clean (we'll use --fix locally for formatting)
disabled_rules:
  - line_length
  - cyclomatic_complexity
  - function_body_length
  - type_body_length
  - file_length
  - comma
  - trailing_whitespace
  - vertical_whitespace
  - opening_brace
  - closing_brace
  - statement_position
  - colon
  - trailing_newline
  - leading_whitespace
  - file_header
  - todo # TODO: Get rid of other TODOs..

# Turn on a few practical (often-correctable) opt-in rules
opt_in_rules:
  - implicit_optional_initialization
  - redundant_void_return
  - operator_usage_whitespace

# Reasonable thresholds (tweak later)
identifier_name:
  min_length: 2
type_name:
  min_length: 2
nesting:
  type_level: 2 # TODO: Reduce this to 1

reporter: "xcode"
